w3c/miniapp

comparison.html
The comparison table got some positive feedback from Google and China community, fix some text issues and update the page UI.
Please refer to https://ibelem.github.io/mini-app-white-paper/comparison.html 
@Honry @xueyuanjia @xfq PTAL
=> [Comparison] Update comparison table and UI

charter.html
per https://www.w3.org/2019/12/05-miniapp-minutes.html
=> Finalize the charter

specs/uri/index.html
added Chinese translation of SoTD.
=> SoTD in zh.

specs/manifest/index.html, specs/packaging/index.html
@Shouqun @zhiqiangyu @QingAn @Sharonzd
=> add more window styles

specs/packaging/index.html
@Shouqun @zhiqiangyu @QingAn @Sharonzd
=> add common specs

specs/manifest/index.html
@zhiqiangyu @QingAn @Sharonzd @Shouqun
=> add manifest contrast and packaging reference

specs/packaging/index.html
Add more feature descriptions for miniapp packages.
=> Update Abstract of Packaging Spec

specs/uri/index.html
Also changed "must" to "need to", since we usually don't use RFC 2119 words in non-normative sections.
=> Mention UTR # 36 in the security section

specs/manifest/index.html, specs/manifest/manifest_schema.json
1. Add the JSON Schema as a seperate file
2. Type clarification of 'non-negative integer' for ' 'versionCode', 'designWidth', 'onReachBottomDistance',
3. Complete the type definition for 'icons'
4. relax some normative language from 'shall' to 'is'.
@Shouqun @ShourenLan @zhiqiangyu
=> Complete the JSON Schema for manifest

specs/manifest/index.html
@zhangyongjing @ShourenLan
Using the ReSpec shortcut. The links will 1) appear in the References section; 2) automatically  update when the URL changes.
=> Simplify the markup

specs/manifest/index.html
=> [manifest] Add intro paragraph to the first section

specs/packaging/index.html
@xfq @ShourenLan @QingAn @zhiqiangyu
=> add 'security' section to packaging

specs/manifest/docs/explainer.md, specs/manifest/index.html
@zhiqiangyu @xfq @Shouqun @zhangyongjing
=> Editorial fixes

specs/packaging/index.html
@xfq @ShourenLan @QingAn @zhiqiangyu
=> add ref to RFC6839

charters/wg-2020.html, charters/wg-2020.zh.html
=> Add new REC-track deliverables without rechartering

charters/wg-2020.html
Fix #81.
(Text is based on https://www.w3.org/2020/05/immersive-Web-wg-charter.html#w3c-coordination )
=> Mention CG in the WG charter

specs/packaging/index.html
Avoid the term "blacklist", to promote inclusive language.
See also: https://github.com/whatwg/html/issues/265
=> Change blacklist to blocklist

charters/wg-2020.html, charters/wg-2020.zh.html
=> Mention DID WG in the Coordination section

white-paper/index.html
To address ISSUE #19 
@ShourenLan @xfq @zhiqiangyu
=> update the Chinese for 'smart assistant'

charters/wg-2020.html, charters/wg-2020.zh.html
=> WG Charter: expand WebAppSec citation

docs/FAQ.md
From https://github.com/w3c/miniapp/issues/109#issuecomment-656636295
=> Add answer from Angel to the FAQ

charters/wg-2020.html
* add reducing development cost as one of the goals of the WG;
* update the description of each spec;
* change MiniApp URI Scheme to a non-normative MiniApp URI Solution;
=> 17-Sep charter discussion

specs/manifest/docs/explainer.md, specs/manifest/index.html
Indication of the WebApp Manifest extension mechanism, including the proprietary member extensions, according to #140 and  #67.
=> Extension of the manifest based on WebApp Manifest mechanisms 

white-paper/index.html
per https://www.w3.org/2021/05/27-miniapp-minutes.html#t08
=> Move white paper to the MiniApps WG

white-paper/index.html
=> Update editors list

white-paper/comparison.html
This PR is a review of the existing table, as I volunteered in #177 . Main changes:
- Status of W3C specifications updated.
- Some new MiniApp APIs included in the table
- Improved readability of the table with Yes/No/Partial values, including the details in a <summary><detail> structure inside the cells. Using homogeneous terms.
- Other minor editorial changes and enhancement of the code (adding `abbr`s, `hreflangs`, etc.)
=> MiniApp-PWA Comparison table updated

white-paper/comparison.html
This PR replaces the #183 I closed. 
The table includes a review of the links and status of the specifications. Also some visual aspects to simplify readability of the content with colors and `<details>+<summary>` elements.
=> Table update and simplifying the view

white-paper/index.html
Sorry for this late PR, I forgot updating this part, based on the discussion in #177. 
I just included the text we discussed in that issue, in case we need to clarify more the differences between PWA and MiniApp. If it's too late for this release, we can keep this PR open for the next version.
=> Clarification of differences between PWA - MiniApp

white-paper/comparison.html
Over the past 1-2 years, the W3C web standards and Chromium's features implementation have been evolving and iterating, with @kenchris 's great help, we found that there are many features/APIs of PWAs that need to be updated.
PTAL @xfq @espinr
=> [Comparison table] W3C and Chromium implementation updates for PWA features

white-paper/index.html
Fixing a typo in the White Paper and minor editorial changes, based on #192
=> Typo fixed and light text refinement in White Paper
